import Context from "@/components/Client";
import Header from "./header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Context >
          <Header />
          {children}
        </Context>
      </body>
    </html>
  );
}
