import Context from "@/components/Client";
import Header from "./header";

export const metadata = {
  title: "Todo App",
  description: "Generated by Shamama Bin Shakil",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="../public/favicon.png"/>
      <body>
        <Context >
          <Header />
          {children}
        </Context>
      </body>
    </html>
  );
}
